# Generated by Django 6.0.5 on 2026-05-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencetable',
            old_name='friendyId',
            new_name='friendlyId',
        ),
    ]
