# Generated by Django 6.0.5 on 2026-06-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_rename_friendyid_referencetable_friendlyid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceTable',
            new_name='reference_table',
        ),
        migrations.RenameField(
            model_name='reference_table',
            old_name='barCode',
            new_name='bar_code',
        ),
    ]
